In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# =========================
# 1. Create XOR Dataset
# =========================
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# =========================
# 2. Build Neural Network Model
# =========================
model = Sequential()

# Hidden layer (at least one hidden layer is required)
model.add(Dense(8, input_dim=2, activation='relu'))

# Output layer
model.add(Dense(1, activation='sigmoid'))

# Compile model
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# =========================
# 3. Train the Model
# =========================
model.fit(X, y, epochs=500, verbose=0)

# =========================
# 4. Test the Model
# =========================
predictions = model.predict(X)
predicted_classes = (predictions > 0.5).astype(int)

print("Inputs:")
print(X)

print("\nActual Outputs:")
print(y)

print("\nPredicted Outputs:")
print(predicted_classes)

# =========================
# 5. Evaluate Accuracy
# =========================
loss, accuracy = model.evaluate(X, y, verbose=0)
print("\nAccuracy:", accuracy)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
Inputs:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Actual Outputs:
[[0]
 [1]
 [1]
 [0]]

Predicted Outputs:
[[0]
 [1]
 [1]
 [0]]

Accuracy: 1.0


In [ ]:
import numpy as np

# ==============================
# 1. XOR Dataset
# ==============================
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([[0],[1],[1],[0]])

# ==============================
# 2. Activation Functions
# ==============================
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

# ==============================
# 3. Network Architecture
# ==============================
np.random.seed(42)

input_neurons = 2
hidden_neurons = 4   # >= 2 needed for XOR
output_neurons = 1

# weights initialization
W1 = np.random.uniform(size=(input_neurons, hidden_neurons))
b1 = np.random.uniform(size=(1, hidden_neurons))

W2 = np.random.uniform(size=(hidden_neurons, output_neurons))
b2 = np.random.uniform(size=(1, output_neurons))

learning_rate = 0.1
epochs = 10000

# ==============================
# 4. Training
# ==============================
converged_epoch = None

for epoch in range(epochs):

    # ----- Forward Pass -----
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    predicted_output = sigmoid(final_input)

    # ----- Error -----
    error = y - predicted_output

    # ----- Backpropagation -----
    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # ----- Update weights -----
    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    # ----- Check convergence -----
    rounded = np.round(predicted_output)

    if np.array_equal(rounded, y):
        converged_epoch = epoch
        print(f"\n🎯 Network converged at epoch: {epoch}")
        break

    # Print loss occasionally
    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch} Loss: {loss:.6f}")

# If not converged
if converged_epoch is None:
    print("\n⚠ Network did NOT fully converge within given epochs")

# ==============================
# 5. Testing the Model
# ==============================
print("\nFinal Predictions:\n")

for i in range(len(X)):
    hidden = sigmoid(np.dot(X[i], W1) + b1)
    output = sigmoid(np.dot(hidden, W2) + b2)
    print(f"Input: {X[i]}  Predicted: {output[0][0]:.4f}  Rounded: {round(output[0][0])}")

Epoch 0 Loss: 0.332183
Epoch 1000 Loss: 0.249044
Epoch 2000 Loss: 0.244445
Epoch 3000 Loss: 0.218039
Epoch 4000 Loss: 0.156119

🎯 Network converged at epoch: 4213

Final Predictions:

Input: [0 0]  Predicted: 0.1915  Rounded: 0
Input: [0 1]  Predicted: 0.7476  Rounded: 1
Input: [1 0]  Predicted: 0.5583  Rounded: 1
Input: [1 1]  Predicted: 0.4997  Rounded: 0
